Overhaul runtime tests
You can now return some cute pithy message along with your test
failure.

diff --git a/runtime_tests b/runtime_tests
--- a/runtime_tests
+++ b/runtime_tests
@@ -11,11 +11,9 @@ echo "Found $testcount tests"
 
 for i in `seq 0 $((testcount - 1))`; do
     echo -n "Running test #$i... "
-    build/sunneed -t $i
-    code=$?
-    if [[ $code != 0 ]]; then
-        echo "$(tput setaf 1)Failed: $code$(tput sgr0)"
-    else
+    build/sunneed -t $i 2>&1 | sed "s/Failure:.*/$(tput setaf 1)\\0$(tput sgr0)/"
+    code=${PIPESTATUS[0]} # Gets us the return value of sunneed (since sed is always 0). Pretty cool huh?
+    if [[ $code == 0 ]]; then
         echo "$(tput setaf 2)Success!$(tput sgr0)"
     fi
 done
